// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghmjtkzrjddfdjautcfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdobWp0a3pyamRkZmRqYXV0Y2ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2ODg5MjIsImV4cCI6MjA4ODI2NDkyMn0.CQVpuaTr33INuL9MBHZgiAem99pXrt07FG_bC-_utXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});